package com.iadv.dukaanlocker.ui.strings

import androidx.compose.runtime.compositionLocalOf

data class AppLanguage(val code: String, val label: String, val native: String)

val appLanguages = listOf(
    AppLanguage("en", "English", "English"),
    AppLanguage("hi", "Hindi", "हिन्दी"),
    AppLanguage("as", "Assamese", "অসমীয়া"),
    AppLanguage("bn", "Bengali", "বাংলা"),
    AppLanguage("gu", "Gujarati", "ગુજરાતી"),
    AppLanguage("kn", "Kannada", "ಕನ್ನಡ"),
    AppLanguage("ml", "Malayalam", "മലയാളം"),
    AppLanguage("mr", "Marathi", "मराठी"),
    AppLanguage("or", "Odia", "ଓଡ଼ିଆ"),
    AppLanguage("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    AppLanguage("ta", "Tamil", "தமிழ்"),
    AppLanguage("te", "Telugu", "తెలుగు")
)

val LocalAppLanguage = compositionLocalOf { "en" }

object AppStrings {
    private val translations: Map<String, Map<String, String>> = mapOf(
        "hi" to mapOf(
            "Secure Business Document Vault" to "सुरक्षित व्यवसाय दस्तावेज़ तिजोरी",
            "Search" to "खोजें",
            "Bank-Grade Security" to "बैंक-स्तरीय सुरक्षा",
            "Your business documents stay encrypted, private & safe in one vault." to "आपके व्यावसायिक दस्तावेज़ एक ही तिजोरी में एन्क्रिप्टेड, निजी और सुरक्षित रहते हैं।",
            "Renewal Reminders" to "नवीनीकरण अनुस्मारक",
            "Never miss an expiry - get timely alerts for every important document." to "समय-सीमा कभी न चूकें - हर महत्वपूर्ण दस्तावेज़ के लिए समय पर सूचना पाएं।",
            "DOCUMENTS YOU CAN STORE" to "आप ये दस्तावेज़ स्टोर कर सकते हैं",
            "GST Certificate" to "GST प्रमाणपत्र",
            "PAN Card" to "PAN कार्ड",
            "Aadhaar Card" to "आधार कार्ड",
            "FSSAI License" to "FSSAI लाइसेंस",
            "Trade License" to "व्यापार लाइसेंस",
            "Shop & Est." to "दुकान और प्रतिष्ठान",
            "Fire NOC" to "अग्नि NOC",
            "Udyam Reg." to "उद्यम पंजीकरण",
            "Drug License" to "औषधि लाइसेंस",
            "Factory License" to "फैक्ट्री लाइसेंस",
            "CATEGORIES" to "श्रेणियाँ",
            "Beauty, Salon & Personal Care" to "सौंदर्य, सैलून और व्यक्तिगत देखभाल",
            "Restaurants, Hotels & Catering" to "रेस्तरां, होटल और कैटरिंग",
            "Food Retail & Grocery" to "खाद्य खुदरा और किराना",
            "Healthcare, Clinics & Diagnostics" to "स्वास्थ्य सेवा, क्लीनिक और डायग्नोस्टिक्स",
            "Pharmacy, Medicines & Medical Equipment" to "फार्मेसी, दवाइयाँ और चिकित्सा उपकरण",
            "Education & Training" to "शिक्षा और प्रशिक्षण",
            "Garments, Textile & Tailoring" to "परिधान, वस्त्र और सिलाई",
            "IT, Software & Digital Services" to "आईटी, सॉफ्टवेयर और डिजिटल सेवाएँ",
            "Electronics, Electrical & Telecom" to "इलेक्ट्रॉनिक्स, इलेक्ट्रिकल और दूरसंचार",
            "Automobile, Transport & Travel" to "ऑटोमोबाइल, परिवहन और यात्रा",
            "Banking, Finance & Insurance" to "बैंकिंग, वित्त और बीमा",
            "Construction Materials, Hardware & Industrial Goods" to "निर्माण सामग्री, हार्डवेयर और औद्योगिक सामान",
            "Courier, Logistics & Warehousing" to "कूरियर, लॉजिस्टिक्स और वेयरहाउसिंग",
            "Professional & Consultancy Services" to "व्यावसायिक और परामर्श सेवाएँ",
            "Others" to "अन्य",
            "GET STARTED" to "शुरू करें",
            "Already have an account? Sign In" to "पहले से खाता है? साइन इन करें",
            "Home" to "होम",
            "Light" to "लाइट",
            "Dark" to "डार्क",
            "Register Now" to "अभी पंजीकरण करें",
            "First time? Create your secure vault" to "पहली बार? अपनी सुरक्षित तिजोरी बनाएं",
            "Returning User?" to "पुराने उपयोगकर्ता?",
            "Business Owner" to "व्यवसाय स्वामी",
            "Sign in with email & password" to "ईमेल और पासवर्ड से साइन इन करें",
            "Manager" to "प्रबंधक",
            "Access assigned businesses with code" to "कोड के साथ निर्धारित व्यवसायों तक पहुंचें",
            "Owner Sign In" to "स्वामी साइन इन",
            "Access your business dashboard" to "अपने व्यवसाय डैशबोर्ड तक पहुंचें",
            "Email Address" to "ईमेल पता",
            "Enter a valid email address" to "मान्य ईमेल पता दर्ज करें",
            "Password" to "पासवर्ड",
            "Enter your password" to "अपना पासवर्ड दर्ज करें",
            "Password is required" to "पासवर्ड आवश्यक है",
            "SECURE ACCESS" to "सुरक्षित पहुंच",
            "Create Account" to "खाता बनाएं",
            "Set up your business document vault" to "अपने व्यवसाय दस्तावेज़ तिजोरी की स्थापना करें",
            "Full Name" to "पूरा नाम",
            "Name is required" to "नाम आवश्यक है",
            "Mobile Number" to "मोबाइल नंबर",
            "Enter a valid 10-digit mobile number" to "मान्य 10 अंकों का मोबाइल नंबर दर्ज करें",
            "8+ chars, upper, lower, digit, special" to "8+ अक्षर, बड़े, छोटे, अंक, विशेष",
            "Enter a password" to "पासवर्ड दर्ज करें",
            "Weak" to "कमजोर",
            "Fair" to "मध्यम",
            "Good" to "अच्छा",
            "Strong" to "मजबूत",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "कम से कम 8 अक्षर जिसमें बड़े, छोटे, अंक और विशेष वर्ण हों",
            "CREATE VAULT" to "तिजोरी बनाएं",
            "Manager Access" to "प्रबंधक पहुंच",
            "Enter access code provided by owner" to "स्वामी द्वारा दिया गया एक्सेस कोड दर्ज करें",
            "Access Code" to "एक्सेस कोड",
            "Invalid access code" to "अमान्य एक्सेस कोड",
            "VERIFY & ACCESS" to "सत्यापित करें और पहुंचें",
            "Secure Business Locker for Your Business" to "आपके व्यवसाय के लिए सुरक्षित व्यवसाय तिजोरी"
        ),
        "as" to mapOf(
            "Secure Business Document Vault" to "সুৰক্ষিত ব্যৱসায় নথি ভল্ট",
            "Search" to "সন্ধান",
            "Bank-Grade Security" to "বেংক-স্তৰীয় সুৰক্ষা",
            "Your business documents stay encrypted, private & safe in one vault." to "আপোনাৰ ব্যৱসায় নথিসমূহ এটা ভল্টত এনক্ৰিপ্টেড, ব্যক্তিগত আৰু সুৰক্ষিত হৈ থাকে।",
            "Renewal Reminders" to "নৱীকৰণ সোঁৱৰণী",
            "Never miss an expiry - get timely alerts for every important document." to "ম্যাদ কেতিয়াও নেৰাখিব - প্ৰতিটো গুৰুত্বপূৰ্ণ নথিৰ বাবে সময়মতে সাৱধানতা বাৰ্তা লাভ কৰক।",
            "DOCUMENTS YOU CAN STORE" to "আপুনি সংৰক্ষণ কৰিব পৰা নথিসমূহ",
            "GST Certificate" to "GST প্ৰমাণপত্ৰ",
            "PAN Card" to "PAN কাৰ্ড",
            "Aadhaar Card" to "আধাৰ কাৰ্ড",
            "FSSAI License" to "FSSAI অনুজ্ঞাপত্ৰ",
            "Trade License" to "বাণিজ্য অনুজ্ঞাপত্ৰ",
            "Shop & Est." to "দোকান আৰু প্ৰতিষ্ঠান",
            "Fire NOC" to "অগ্নি NOC",
            "Udyam Reg." to "উদ্যোগ নিবন্ধন",
            "Drug License" to "ঔষধ অনুজ্ঞাপত্ৰ",
            "Factory License" to "কাৰখানা অনুজ্ঞাপত্ৰ",
            "CATEGORIES" to "শ্ৰেণীসমূহ",
            "Beauty, Salon & Personal Care" to "সৌন্দৰ্য, চেলুন আৰু ব্যক্তিগত যত্ন",
            "Restaurants, Hotels & Catering" to "ৰেষ্টুৰেণ্ট, হোটেল আৰু কেটেৰিং",
            "Food Retail & Grocery" to "খাদ্য খুচুৰা আৰু মুদা",
            "Healthcare, Clinics & Diagnostics" to "স্বাস্থ্যসেৱা, ক্লিনিক আৰু ডায়াগ্ন'ষ্টিক্স",
            "Pharmacy, Medicines & Medical Equipment" to "ফাৰ্মাচী, ঔষধ আৰু চিকিৎসা সঁজুলি",
            "Education & Training" to "শিক্ষা আৰু প্ৰশিক্ষণ",
            "Garments, Textile & Tailoring" to "বস্ত্ৰ, কাপোৰ আৰু চিলাই",
            "IT, Software & Digital Services" to "আইটি, চফ্টৱেৰ আৰু ডিজিটেল সেৱা",
            "Electronics, Electrical & Telecom" to "ইলেক্ট্ৰনিক্স, ইলেক্ট্ৰিকেল আৰু দূৰসংযোগ",
            "Automobile, Transport & Travel" to "অটোম'বাইল, পৰিবহণ আৰু ভ্ৰমণ",
            "Banking, Finance & Insurance" to "বেংকিং, বিত্ত আৰু বীমা",
            "Construction Materials, Hardware & Industrial Goods" to "নিৰ্মাণ সামগ্ৰী, হাৰ্ডৱেৰ আৰু উদ্যোগিক সামগ্ৰী",
            "Courier, Logistics & Warehousing" to "কুৰিয়াৰ, লজিষ্টিক্স আৰু গুদাম",
            "Professional & Consultancy Services" to "বৃত্তিগত আৰু পৰামৰ্শ সেৱা",
            "Others" to "অন্যান্য",
            "GET STARTED" to "আৰম্ভ কৰক",
            "Already have an account? Sign In" to "আগৰে পৰা একাউণ্ট আছে? চাইন ইন কৰক",
            "Home" to "হোম",
            "Light" to "লাইট",
            "Dark" to "ডাৰ্ক",
            "Register Now" to "এতিয়া পঞ্জীয়ন কৰক",
            "First time? Create your secure vault" to "প্ৰথমবাৰ? আপোনাৰ সুৰক্ষিত ভল্ট সৃষ্টি কৰক",
            "Returning User?" to "পূৰ্বৰ ব্যৱহাৰকাৰী?",
            "Business Owner" to "ব্যৱসায় গৰাকী",
            "Sign in with email & password" to "ইমেইল আৰু পাছৱৰ্ডৰে চাইন ইন কৰক",
            "Manager" to "পৰিচালক",
            "Access assigned businesses with code" to "ক'ডৰ সৈতে নিৰ্ধাৰিত ব্যৱসায়সমূহত প্ৰৱেশ কৰক",
            "Owner Sign In" to "গৰাকী চাইন ইন",
            "Access your business dashboard" to "আপোনাৰ ব্যৱসায় ডেশ্বব'ৰ্ডত প্ৰৱেশ কৰক",
            "Email Address" to "ইমেইল ঠিকনা",
            "Enter a valid email address" to "বৈধ ইমেইল ঠিকনা লিখক",
            "Password" to "পাছৱৰ্ড",
            "Enter your password" to "আপোনাৰ পাছৱৰ্ড লিখক",
            "Password is required" to "পাছৱৰ্ড প্ৰয়োজন",
            "SECURE ACCESS" to "সুৰক্ষিত প্ৰৱেশ",
            "Create Account" to "একাউণ্ট সৃষ্টি কৰক",
            "Set up your business document vault" to "আপোনাৰ ব্যৱসায় নথি ভল্ট স্থাপন কৰক",
            "Full Name" to "সম্পূৰ্ণ নাম",
            "Name is required" to "নাম প্ৰয়োজন",
            "Mobile Number" to "ম'বাইল নম্বৰ",
            "Enter a valid 10-digit mobile number" to "বৈধ 10-অংকৰ ম'বাইল নম্বৰ লিখক",
            "8+ chars, upper, lower, digit, special" to "8+ আখৰ, বৰ, সৰু, অংক, বিশেষ",
            "Enter a password" to "পাছৱৰ্ড লিখক",
            "Weak" to "দুৰ্বল",
            "Fair" to "মধ্যম",
            "Good" to "ভাল",
            "Strong" to "শক্তিশালী",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "অন্তত 8 আখৰ বৰ, সৰু আখৰ, অংক আৰু বিশেষ চিহ্নসহ হ'ব লাগিব",
            "CREATE VAULT" to "ভল্ট সৃষ্টি কৰক",
            "Manager Access" to "পৰিচালক প্ৰৱেশ",
            "Enter access code provided by owner" to "গৰাকীয়ে দিয়া প্ৰৱেশ ক'ড লিখক",
            "Access Code" to "প্ৰৱেশ ক'ড",
            "Invalid access code" to "অবৈধ প্ৰৱেশ ক'ড",
            "VERIFY & ACCESS" to "সত্যাপন কৰি প্ৰৱেশ কৰক",
            "Secure Business Locker for Your Business" to "আপোনাৰ ব্যৱসায়ৰ বাবে সুৰক্ষিত ব্যৱসায় লকাৰ"
        ),
        "bn" to mapOf(
            "Secure Business Document Vault" to "সুরক্ষিত ব্যবসায়িক নথির ভল্ট",
            "Search" to "অনুসন্ধান",
            "Bank-Grade Security" to "ব্যাংক-মানের নিরাপত্তা",
            "Your business documents stay encrypted, private & safe in one vault." to "আপনার ব্যবসায়িক নথিগুলি একটি ভল্টে এনক্রিপ্টেড, ব্যক্তিগত ও নিরাপদ থাকে।",
            "Renewal Reminders" to "নবায়ন স্মারক",
            "Never miss an expiry - get timely alerts for every important document." to "মেয়াদ কখনো মিস করবেন না - প্রতিটি গুরুত্বপূর্ণ নথির জন্য সময়মতো সতর্কবার্তা পান।",
            "DOCUMENTS YOU CAN STORE" to "আপনি যেসব নথি সংরক্ষণ করতে পারেন",
            "GST Certificate" to "GST সার্টিফিকেট",
            "PAN Card" to "PAN কার্ড",
            "Aadhaar Card" to "আধার কার্ড",
            "FSSAI License" to "FSSAI লাইসেন্স",
            "Trade License" to "ট্রেড লাইসেন্স",
            "Shop & Est." to "দোকান ও প্রতিষ্ঠান",
            "Fire NOC" to "অগ্নি NOC",
            "Udyam Reg." to "উদ্যম নিবন্ধন",
            "Drug License" to "ড্রাগ লাইসেন্স",
            "Factory License" to "ফ্যাক্টরি লাইসেন্স",
            "CATEGORIES" to "বিভাগসমূহ",
            "Beauty, Salon & Personal Care" to "সৌন্দর্য, সেলুন ও ব্যক্তিগত যত্ন",
            "Restaurants, Hotels & Catering" to "রেস্তোরাঁ, হোটেল ও ক্যাটারিং",
            "Food Retail & Grocery" to "খাদ্য খুচরা ও মুদি",
            "Healthcare, Clinics & Diagnostics" to "স্বাস্থ্যসেবা, ক্লিনিক ও ডায়াগনস্টিকস",
            "Pharmacy, Medicines & Medical Equipment" to "ফার্মেসি, ওষুধ ও চিকিৎসা সরঞ্জাম",
            "Education & Training" to "শিক্ষা ও প্রশিক্ষণ",
            "Garments, Textile & Tailoring" to "পোশাক, বস্ত্র ও দর্জি",
            "IT, Software & Digital Services" to "আইটি, সফটওয়্যার ও ডিজিটাল পরিষেবা",
            "Electronics, Electrical & Telecom" to "ইলেকট্রনিক্স, ইলেকট্রিক্যাল ও টেলিকম",
            "Automobile, Transport & Travel" to "অটোমোবাইল, পরিবহন ও ভ্রমণ",
            "Banking, Finance & Insurance" to "ব্যাংকিং, অর্থ ও বীমা",
            "Construction Materials, Hardware & Industrial Goods" to "নির্মাণ সামগ্রী, হার্ডওয়্যার ও শিল্প পণ্য",
            "Courier, Logistics & Warehousing" to "কুরিয়ার, লজিস্টিকস ও ওয়্যারহাউজিং",
            "Professional & Consultancy Services" to "পেশাদার ও পরামর্শ পরিষেবা",
            "Others" to "অন্যান্য",
            "GET STARTED" to "শুরু করুন",
            "Already have an account? Sign In" to "ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন",
            "Home" to "হোম",
            "Light" to "লাইট",
            "Dark" to "ডার্ক",
            "Register Now" to "এখন নিবন্ধন করুন",
            "First time? Create your secure vault" to "প্রথমবার? আপনার সুরক্ষিত ভল্ট তৈরি করুন",
            "Returning User?" to "পুরনো ব্যবহারকারী?",
            "Business Owner" to "ব্যবসার মালিক",
            "Sign in with email & password" to "ইমেইল ও পাসওয়ার্ড দিয়ে সাইন ইন করুন",
            "Manager" to "ম্যানেজার",
            "Access assigned businesses with code" to "কোড দিয়ে নির্ধারিত ব্যবসায় প্রবেশ করুন",
            "Owner Sign In" to "মালিক সাইন ইন",
            "Access your business dashboard" to "আপনার ব্যবসা ড্যাশবোর্ডে প্রবেশ করুন",
            "Email Address" to "ইমেইল ঠিকানা",
            "Enter a valid email address" to "সঠিক ইমেইল ঠিকানা লিখুন",
            "Password" to "পাসওয়ার্ড",
            "Enter your password" to "আপনার পাসওয়ার্ড লিখুন",
            "Password is required" to "পাসওয়ার্ড প্রয়োজন",
            "SECURE ACCESS" to "নিরাপদ প্রবেশ",
            "Create Account" to "অ্যাকাউন্ট তৈরি করুন",
            "Set up your business document vault" to "আপনার ব্যবসা নথির ভল্ট সেট আপ করুন",
            "Full Name" to "পুরো নাম",
            "Name is required" to "নাম প্রয়োজন",
            "Mobile Number" to "মোবাইল নম্বর",
            "Enter a valid 10-digit mobile number" to "সঠিক ১০-অঙ্কের মোবাইল নম্বর লিখুন",
            "8+ chars, upper, lower, digit, special" to "৮+ অক্ষর, বড়, ছোট, সংখ্যা, বিশেষ",
            "Enter a password" to "পাসওয়ার্ড লিখুন",
            "Weak" to "দুর্বল",
            "Fair" to "মাঝারি",
            "Good" to "ভালো",
            "Strong" to "শক্তিশালী",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "কমপক্ষে ৮ অক্ষর বড়, ছোট হাতের, সংখ্যা ও বিশেষ চিহ্নসহ হতে হবে",
            "CREATE VAULT" to "ভল্ট তৈরি করুন",
            "Manager Access" to "ম্যানেজার প্রবেশ",
            "Enter access code provided by owner" to "মালিকের দেওয়া অ্যাক্সেস কোড লিখুন",
            "Access Code" to "অ্যাক্সেস কোড",
            "Invalid access code" to "অবৈধ অ্যাক্সেস কোড",
            "VERIFY & ACCESS" to "যাচাই করুন ও প্রবেশ করুন",
            "Secure Business Locker for Your Business" to "আপনার ব্যবসার জন্য সুরক্ষিত ব্যবসা লকার"
        ),
        "gu" to mapOf(
            "Secure Business Document Vault" to "સુરક્ષિત બિઝનેસ ડોક્યુમેન્ટ વૉલ્ટ",
            "Search" to "શોધો",
            "Bank-Grade Security" to "બેંક-ગ્રેડ સુરક્ષા",
            "Your business documents stay encrypted, private & safe in one vault." to "તમારા બિઝનેસ દસ્તાવેજો એક જ વૉલ્ટમાં એન્ક્રિપ્ટેડ, ખાનગી અને સુરક્ષિત રહે છે.",
            "Renewal Reminders" to "નવીકરણ રિમાઇન્ડર",
            "Never miss an expiry - get timely alerts for every important document." to "સમયમર્યાદા ક્યારેય ન ચૂકો - દરેક મહત્વપૂર્ણ દસ્તાવેજ માટે સમયસર ચેતવણી મેળવો.",
            "DOCUMENTS YOU CAN STORE" to "તમે આ દસ્તાવેજો સ્ટોર કરી શકો છો",
            "GST Certificate" to "GST પ્રમાણપત્ર",
            "PAN Card" to "PAN કાર્ડ",
            "Aadhaar Card" to "આધાર કાર્ડ",
            "FSSAI License" to "FSSAI લાઇસન્સ",
            "Trade License" to "ટ્રેડ લાઇસન્સ",
            "Shop & Est." to "દુકાન અને સંસ્થા",
            "Fire NOC" to "અગ્નિ NOC",
            "Udyam Reg." to "ઉદ્યમ નોંધણી",
            "Drug License" to "દવા લાઇસન્સ",
            "Factory License" to "ફેક્ટરી લાઇસન્સ",
            "CATEGORIES" to "શ્રેણીઓ",
            "Beauty, Salon & Personal Care" to "સૌંદર્ય, સલૂન અને વ્યક્તિગત સંભાળ",
            "Restaurants, Hotels & Catering" to "રેસ્ટોરન્ટ, હોટેલ અને કેટરિંગ",
            "Food Retail & Grocery" to "ફૂડ રિટેલ અને કરિયાણા",
            "Healthcare, Clinics & Diagnostics" to "હેલ્થકેર, ક્લિનિક અને ડાયગ્નોસ્ટિક્સ",
            "Pharmacy, Medicines & Medical Equipment" to "ફાર્મસી, દવાઓ અને તબીબી સાધનો",
            "Education & Training" to "શિક્ષણ અને તાલીમ",
            "Garments, Textile & Tailoring" to "વસ્ત્રો, કાપડ અને ટેલરિંગ",
            "IT, Software & Digital Services" to "આઇટી, સોફ્ટવેર અને ડિજિટલ સેવાઓ",
            "Electronics, Electrical & Telecom" to "ઇલેક્ટ્રોનિક્સ, ઇલેક્ટ્રિકલ અને ટેલિકોમ",
            "Automobile, Transport & Travel" to "ઓટોમોબાઇલ, પરિવહન અને મુસાફરી",
            "Banking, Finance & Insurance" to "બેંકિંગ, ફાઇનાન્સ અને વીમો",
            "Construction Materials, Hardware & Industrial Goods" to "બાંધકામ સામગ્રી, હાર્ડવેર અને ઔદ્યોગિક માલ",
            "Courier, Logistics & Warehousing" to "કુરિયર, લોજિસ્ટિક્સ અને વેરહાઉસિંગ",
            "Professional & Consultancy Services" to "વ્યાવસાયિક અને સલાહકાર સેવાઓ",
            "Others" to "અન્ય",
            "GET STARTED" to "શરૂ કરો",
            "Already have an account? Sign In" to "પહેલેથી ખાતું છે? સાઇન ઇન કરો",
            "Home" to "હોમ",
            "Light" to "લાઇટ",
            "Dark" to "ડાર્ક",
            "Register Now" to "હવે નોંધણી કરો",
            "First time? Create your secure vault" to "પ્રથમ વખત? તમારો સુરક્ષિત વૉલ્ટ બનાવો",
            "Returning User?" to "પરિચિત વપરાશકર્તા?",
            "Business Owner" to "વ્યવસાય માલિક",
            "Sign in with email & password" to "ઇમેઇલ અને પાસવર્ડથી સાઇન ઇન કરો",
            "Manager" to "મેનેજર",
            "Access assigned businesses with code" to "કોડ સાથે સોંપાયેલ વ્યવસાયોમાં પ્રવેશ કરો",
            "Owner Sign In" to "માલિક સાઇન ઇન",
            "Access your business dashboard" to "તમારા વ્યવસાય ડેશબોર્ડમાં પ્રવેશ કરો",
            "Email Address" to "ઇમેઇલ સરનામું",
            "Enter a valid email address" to "માન્ય ઇમેઇલ સરનામું દાખલ કરો",
            "Password" to "પાસવર્ડ",
            "Enter your password" to "તમારો પાસવર્ડ દાખલ કરો",
            "Password is required" to "પાસવર્ડ જરૂરી છે",
            "SECURE ACCESS" to "સુરક્ષિત પ્રવેશ",
            "Create Account" to "ખાતું બનાવો",
            "Set up your business document vault" to "તમારો વ્યવસાય દસ્તાવેજ વૉલ્ટ સેટ કરો",
            "Full Name" to "પૂરું નામ",
            "Name is required" to "નામ જરૂરી છે",
            "Mobile Number" to "મોબાઇલ નંબર",
            "Enter a valid 10-digit mobile number" to "માન્ય 10-અંકનો મોબાઇલ નંબર દાખલ કરો",
            "8+ chars, upper, lower, digit, special" to "8+ અક્ષર, મોટા, નાના, અંક, ખાસ",
            "Enter a password" to "પાસવર્ડ દાખલ કરો",
            "Weak" to "નબળું",
            "Fair" to "સરેરાશ",
            "Good" to "સારું",
            "Strong" to "મજબૂત",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "ઓછામાં ઓછા 8 અક્ષર મોટા, નાના, અંક અને ખાસ ચિહ્ન સાથે હોવા જોઈએ",
            "CREATE VAULT" to "વૉલ્ટ બનાવો",
            "Manager Access" to "મેનેજર પ્રવેશ",
            "Enter access code provided by owner" to "માલિક દ્વારા આપેલ એક્સેસ કોડ દાખલ કરો",
            "Access Code" to "એક્સેસ કોડ",
            "Invalid access code" to "અમાન્ય એક્સેસ કોડ",
            "VERIFY & ACCESS" to "ચકાસો અને પ્રવેશ કરો",
            "Secure Business Locker for Your Business" to "તમારા વ્યવસાય માટે સુરક્ષિત બિઝનેસ લોકર"
        ),
        "kn" to mapOf(
            "Secure Business Document Vault" to "ಸುರಕ್ಷಿತ ವ್ಯಾಪಾರ ದಾಖಲೆ ವಾಲ್ಟ್",
            "Search" to "ಹುಡುಕಿ",
            "Bank-Grade Security" to "ಬ್ಯಾಂಕ್-ಮಟ್ಟದ ಭದ್ರತೆ",
            "Your business documents stay encrypted, private & safe in one vault." to "ನಿಮ್ಮ ವ್ಯಾಪಾರ ದಾಖಲೆಗಳು ಒಂದೇ ವಾಲ್ಟ್ನಲ್ಲಿ ಎನ್ಕ್ರಿಪ್ಟ್, ಖಾಸಗಿ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿರುತ್ತವೆ.",
            "Renewal Reminders" to "ನವೀಕರಣ ಜ್ಞಾಪನೆ",
            "Never miss an expiry - get timely alerts for every important document." to "ಮುಕ್ತಾಯವನ್ನು ಎಂದಿಗೂ ತಪ್ಪಿಸಿಕೊಳ್ಳಬೇಡಿ - ಪ್ರತಿ ಪ್ರಮುಖ ದಾಖಲೆಗೆ ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಎಚ್ಚರಿಕೆ ಪಡೆಯಿರಿ.",
            "DOCUMENTS YOU CAN STORE" to "ನೀವು ಸಂಗ್ರಹಿಸಬಹುದಾದ ದಾಖಲೆಗಳು",
            "GST Certificate" to "GST ಪ್ರಮಾಣಪತ್ರ",
            "PAN Card" to "PAN ಕಾರ್ಡ್",
            "Aadhaar Card" to "ಆಧಾರ ಕಾರ್ಡ್",
            "FSSAI License" to "FSSAI ಪರವಾನಗಿ",
            "Trade License" to "ವ್ಯಾಪಾರ ಪರವಾನಗಿ",
            "Shop & Est." to "ಅಂಗಡಿ ಮತ್ತು ಸ್ಥಾಪನೆ",
            "Fire NOC" to "ಅಗ್ನಿ NOC",
            "Udyam Reg." to "ಉದ್ಯಮ ನೋಂದಣಿ",
            "Drug License" to "ಔಷಧಿ ಪರವಾನಗಿ",
            "Factory License" to "ಕಾರ್ಖಾನೆ ಪರವಾನಗಿ",
            "CATEGORIES" to "ವರ್ಗಗಳು",
            "Beauty, Salon & Personal Care" to "ಸೌಂದರ್ಯ, ಸಲೂನ್ ಮತ್ತು ವೈಯಕ್ತಿಕ ಆರೈಕೆ",
            "Restaurants, Hotels & Catering" to "ರೆಸ್ಟೋರೆಂಟ್, ಹೋಟೆಲ್ ಮತ್ತು ಕೇಟರಿಂಗ್",
            "Food Retail & Grocery" to "ಆಹಾರ ಚಿಲ್ಲರೆ ಮತ್ತು ದಿನಸಿ",
            "Healthcare, Clinics & Diagnostics" to "ಆರೋಗ್ಯ ಸೇವೆ, ಕ್ಲಿನಿಕ್ ಮತ್ತು ಡಯಾಗ್ನೋಸ್ಟಿಕ್ಸ್",
            "Pharmacy, Medicines & Medical Equipment" to "ಔಷಧಾಲಯ, ಔಷಧಗಳು ಮತ್ತು ವೈದ್ಯಕೀಯ ಉಪಕರಣ",
            "Education & Training" to "ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ",
            "Garments, Textile & Tailoring" to "ಉಡುಪು, ಜವಳಿ ಮತ್ತು ಹೊಲಿಗೆ",
            "IT, Software & Digital Services" to "ಐಟಿ, ಸಾಫ್ಟ್ವೇರ್ ಮತ್ತು ಡಿಜಿಟಲ್ ಸೇವೆಗಳು",
            "Electronics, Electrical & Telecom" to "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್, ವಿದ್ಯುತ್ ಮತ್ತು ದೂರಸಂಪರ್ಕ",
            "Automobile, Transport & Travel" to "ಆಟೋಮೊಬೈಲ್, ಸಾರಿಗೆ ಮತ್ತು ಪ್ರಯಾಣ",
            "Banking, Finance & Insurance" to "ಬ್ಯಾಂಕಿಂಗ್, ಹಣಕಾಸು ಮತ್ತು ವಿಮೆ",
            "Construction Materials, Hardware & Industrial Goods" to "ನಿರ್ಮಾಣ ಸಾಮಗ್ರಿ, ಹಾರ್ಡ್ವೇರ್ ಮತ್ತು ಕೈಗಾರಿಕಾ ಸರಕು",
            "Courier, Logistics & Warehousing" to "ಕೊರಿಯರ್, ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮತ್ತು ಗೋದಾಮು",
            "Professional & Consultancy Services" to "ವೃತ್ತಿಪರ ಮತ್ತು ಸಲಹಾ ಸೇವೆಗಳು",
            "Others" to "ಇತರೆ",
            "GET STARTED" to "ಪ್ರಾರಂಭಿಸಿ",
            "Already have an account? Sign In" to "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಸೈನ್ ಇನ್ ಮಾಡಿ",
            "Home" to "ಹೋಮ್",
            "Light" to "ಲೈಟ್",
            "Dark" to "ಡಾರ್ಕ್",
            "Register Now" to "ಈಗ ನೋಂದಾಯಿಸಿ",
            "First time? Create your secure vault" to "ಮೊದಲ ಬಾರಿ? ನಿಮ್ಮ ಸುರಕ್ಷಿತ ವಾಲ್ಟ್ ರಚಿಸಿ",
            "Returning User?" to "ಹಿಂದಿನ ಬಳಕೆದಾರರೇ?",
            "Business Owner" to "ವ್ಯಾಪಾರ ಮಾಲೀಕ",
            "Sign in with email & password" to "ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್ವರ್ಡ್‌ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
            "Manager" to "ವ್ಯವಸ್ಥಾಪಕ",
            "Access assigned businesses with code" to "ಕೋಡ್‌ನೊಂದಿಗೆ ನಿಯೋಜಿತ ವ್ಯವಹಾರಗಳನ್ನು ಪ್ರವೇಶಿಸಿ",
            "Owner Sign In" to "ಮಾಲೀಕ ಸೈನ್ ಇನ್",
            "Access your business dashboard" to "ನಿಮ್ಮ ವ್ಯಾಪಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ",
            "Email Address" to "ಇಮೇಲ್ ವಿಳಾಸ",
            "Enter a valid email address" to "ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
            "Password" to "ಪಾಸ್ವರ್ಡ್",
            "Enter your password" to "ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ",
            "Password is required" to "ಪಾಸ್ವರ್ಡ್ ಅಗತ್ಯವಿದೆ",
            "SECURE ACCESS" to "ಸುರಕ್ಷಿತ ಪ್ರವೇಶ",
            "Create Account" to "ಖಾತೆ ರಚಿಸಿ",
            "Set up your business document vault" to "ನಿಮ್ಮ ವ್ಯಾಪಾರ ದಾಖಲೆ ವಾಲ್ಟ್ ಅನ್ನು ಸ್ಥಾಪಿಸಿ",
            "Full Name" to "ಪೂರ್ಣ ಹೆಸರು",
            "Name is required" to "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
            "Mobile Number" to "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
            "Enter a valid 10-digit mobile number" to "ಮಾನ್ಯ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            "8+ chars, upper, lower, digit, special" to "8+ ಅಕ್ಷರಗಳು, ದೊಡ್ಡ, ಸಣ್ಣ, ಅಂಕಿ, ವಿಶೇಷ",
            "Enter a password" to "ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ",
            "Weak" to "ದುರ್ಬಲ",
            "Fair" to "ಮಧ್ಯಮ",
            "Good" to "ಒಳ್ಳೆಯದು",
            "Strong" to "ಬಲವಾದ",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು ದೊಡ್ಡಕ್ಷರ, ಸಣ್ಣಕ್ಷರ, ಅಂಕಿ ಮತ್ತು ವಿಶೇಷ ಅಕ್ಷರದೊಂದಿಗೆ ಇರಬೇಕು",
            "CREATE VAULT" to "ವಾಲ್ಟ್ ರಚಿಸಿ",
            "Manager Access" to "ವ್ಯವಸ್ಥಾಪಕ ಪ್ರವೇಶ",
            "Enter access code provided by owner" to "ಮಾಲೀಕರು ನೀಡಿದ ಪ್ರವೇಶ ಕೋಡ್ ನಮೂದಿಸಿ",
            "Access Code" to "ಪ್ರವೇಶ ಕೋಡ್",
            "Invalid access code" to "ಅಮಾನ್ಯ ಪ್ರವೇಶ ಕೋಡ್",
            "VERIFY & ACCESS" to "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪ್ರವೇಶಿಸಿ",
            "Secure Business Locker for Your Business" to "ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕಾಗಿ ಸುರಕ್ಷಿತ ವ್ಯಾಪಾರ ಲಾಕರ್"
        ),
        "ml" to mapOf(
            "Secure Business Document Vault" to "സുരക്ഷിത ബിസിനസ് ഡോക്യുമെന്റ് വോൾട്ട്",
            "Search" to "തിരയുക",
            "Bank-Grade Security" to "ബാങ്ക്-നിലവാര സുരക്ഷ",
            "Your business documents stay encrypted, private & safe in one vault." to "നിങ്ങളുടെ ബിസിനസ് രേഖകൾ ഒരു വോൾട്ടിൽ എൻക്രിപ്റ്റ് ചെയ്ത്, സ്വകാര്യവും സുരക്ഷിതവുമായി നിലനിൽക്കുന്നു.",
            "Renewal Reminders" to "പുതുക്കൽ ഓർമ്മപ്പെടുത്തലുകൾ",
            "Never miss an expiry - get timely alerts for every important document." to "കാലഹരണപ്പെടൽ ഒരിക്കലും നഷ്ടപ്പെടുത്തരുത് - ഓരോ പ്രധാന രേഖയ്ക്കും സമയോചിതമായ അറിയിപ്പുകൾ നേടുക.",
            "DOCUMENTS YOU CAN STORE" to "നിങ്ങൾക്ക് സൂക്ഷിക്കാവുന്ന രേഖകൾ",
            "GST Certificate" to "GST സർട്ടിഫിക്കറ്റ്",
            "PAN Card" to "PAN കാർഡ്",
            "Aadhaar Card" to "ആധാർ കാർഡ്",
            "FSSAI License" to "FSSAI ലൈസൻസ്",
            "Trade License" to "വ്യാപാര ലൈസൻസ്",
            "Shop & Est." to "കടയും സ്ഥാപനവും",
            "Fire NOC" to "അഗ്നി NOC",
            "Udyam Reg." to "ഉദ്യം രജിസ്ട്രേഷൻ",
            "Drug License" to "മരുന്ന് ലൈസൻസ്",
            "Factory License" to "ഫാക്ടറി ലൈസൻസ്",
            "CATEGORIES" to "വിഭാഗങ്ങൾ",
            "Beauty, Salon & Personal Care" to "സൗന്ദര്യം, സലൂൺ, വ്യക്തിഗത പരിചരണം",
            "Restaurants, Hotels & Catering" to "റെസ്റ്റോറന്റ്, ഹോട്ടൽ, കാറ്ററിംഗ്",
            "Food Retail & Grocery" to "ഭക്ഷണ റീട്ടെയിൽ, പലചരക്ക്",
            "Healthcare, Clinics & Diagnostics" to "ആരോഗ്യ സംരക്ഷണം, ക്ലിനിക്കുകൾ, ഡയഗ്നോസ്റ്റിക്സ്",
            "Pharmacy, Medicines & Medical Equipment" to "മരുന്നുകട, മരുന്നുകൾ, മെഡിക്കൽ ഉപകരണങ്ങൾ",
            "Education & Training" to "വിദ്യാഭ്യാസം, പരിശീലനം",
            "Garments, Textile & Tailoring" to "വസ്ത്രം, തുണി, ടൈലറിംഗ്",
            "IT, Software & Digital Services" to "ഐടി, സോഫ്റ്റ്വെയർ, ഡിജിറ്റൽ സേവനങ്ങൾ",
            "Electronics, Electrical & Telecom" to "ഇലക്ട്രോണിക്സ്, ഇലക്ട്രിക്കൽ, ടെലികോം",
            "Automobile, Transport & Travel" to "ഓട്ടോമൊബൈൽ, ഗതാഗതം, യാത്ര",
            "Banking, Finance & Insurance" to "ബാങ്കിംഗ്, ധനകാര്യം, ഇൻഷുറൻസ്",
            "Construction Materials, Hardware & Industrial Goods" to "നിർമ്മാണ സാമഗ്രികൾ, ഹാർഡ്വെയർ, വ്യാവസായിക സാധനങ്ങൾ",
            "Courier, Logistics & Warehousing" to "കൊറിയർ, ലോജിസ്റ്റിക്സ്, വെയർഹൗസിംഗ്",
            "Professional & Consultancy Services" to "പ്രൊഫഷണൽ, കൺസൾട്ടൻസി സേവനങ്ങൾ",
            "Others" to "മറ്റുള്ളവ",
            "GET STARTED" to "ആരംഭിക്കുക",
            "Already have an account? Sign In" to "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? സൈൻ ഇൻ ചെയ്യുക",
            "Home" to "ഹോം",
            "Light" to "ലൈറ്റ്",
            "Dark" to "ഡാർക്ക്",
            "Register Now" to "ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക",
            "First time? Create your secure vault" to "ആദ്യമായാണോ? നിങ്ങളുടെ സുരക്ഷിത വോൾട്ട് സൃഷ്ടിക്കുക",
            "Returning User?" to "മുൻ ഉപയോക്താവാണോ?",
            "Business Owner" to "ബിസിനസ് ഉടമ",
            "Sign in with email & password" to "ഇമെയിലും പാസ്വേഡും ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക",
            "Manager" to "മാനേജർ",
            "Access assigned businesses with code" to "കോഡ് ഉപയോഗിച്ച് നിയുക്ത ബിസിനസുകളിലേക്ക് പ്രവേശിക്കുക",
            "Owner Sign In" to "ഉടമ സൈൻ ഇൻ",
            "Access your business dashboard" to "നിങ്ങളുടെ ബിസിനസ് ഡാഷ്ബോർഡിലേക്ക് പ്രവേശിക്കുക",
            "Email Address" to "ഇമെയിൽ വിലാസം",
            "Enter a valid email address" to "സാധുവായ ഇമെയിൽ വിലാസം നൽകുക",
            "Password" to "പാസ്വേഡ്",
            "Enter your password" to "നിങ്ങളുടെ പാസ്വേഡ് നൽകുക",
            "Password is required" to "പാസ്വേഡ് ആവശ്യമാണ്",
            "SECURE ACCESS" to "സുരക്ഷിത പ്രവേശനം",
            "Create Account" to "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
            "Set up your business document vault" to "നിങ്ങളുടെ ബിസിനസ് രേഖ വോൾട്ട് സജ്ജമാക്കുക",
            "Full Name" to "മുഴുവൻ പേര്",
            "Name is required" to "പേര് ആവശ്യമാണ്",
            "Mobile Number" to "മൊബൈൽ നമ്പർ",
            "Enter a valid 10-digit mobile number" to "സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
            "8+ chars, upper, lower, digit, special" to "8+ അക്ഷരങ്ങൾ, വലിയ, ചെറിയ, അക്കം, പ്രത്യേകം",
            "Enter a password" to "പാസ്വേഡ് നൽകുക",
            "Weak" to "ദുർബലം",
            "Fair" to "ശരാശരി",
            "Good" to "നല്ലത്",
            "Strong" to "ശക്തമായ",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ വലിയ, ചെറിയ അക്ഷരങ്ങൾ, അക്കം, പ്രത്യേക ചിഹ്നം എന്നിവ ഉണ്ടായിരിക്കണം",
            "CREATE VAULT" to "വോൾട്ട് സൃഷ്ടിക്കുക",
            "Manager Access" to "മാനേജർ പ്രവേശനം",
            "Enter access code provided by owner" to "ഉടമ നൽകിയ ആക്സസ് കോഡ് നൽകുക",
            "Access Code" to "ആക്സസ് കോഡ്",
            "Invalid access code" to "അസാധുവായ ആക്സസ് കോഡ്",
            "VERIFY & ACCESS" to "പരിശോധിച്ച് പ്രവേശിക്കുക",
            "Secure Business Locker for Your Business" to "നിങ്ങളുടെ ബിസിനസിനായി സുരക്ഷിത ബിസിനസ് ലോക്കർ"
        ),
        "mr" to mapOf(
            "Secure Business Document Vault" to "सुरक्षित व्यवसाय दस्तऐवज व्हॉल्ट",
            "Search" to "शोधा",
            "Bank-Grade Security" to "बँक-दर्जाची सुरक्षा",
            "Your business documents stay encrypted, private & safe in one vault." to "तुमचे व्यवसाय दस्तऐवज एकाच व्हॉल्टमध्ये एन्क्रिप्टेड, खाजगी आणि सुरक्षित राहतात.",
            "Renewal Reminders" to "नूतनीकरण स्मरणपत्रे",
            "Never miss an expiry - get timely alerts for every important document." to "मुदत कधीही चुकवू नका - प्रत्येक महत्त्वाच्या दस्तऐवजासाठी वेळेवर सूचना मिळवा.",
            "DOCUMENTS YOU CAN STORE" to "तुम्ही स्टोअर करू शकता असे दस्तऐवज",
            "GST Certificate" to "GST प्रमाणपत्र",
            "PAN Card" to "PAN कार्ड",
            "Aadhaar Card" to "आधार कार्ड",
            "FSSAI License" to "FSSAI परवाना",
            "Trade License" to "व्यापार परवाना",
            "Shop & Est." to "दुकान आणि प्रतिष्ठान",
            "Fire NOC" to "अग्निशमन NOC",
            "Udyam Reg." to "उद्यम नोंदणी",
            "Drug License" to "औषध परवाना",
            "Factory License" to "कारखाना परवाना",
            "CATEGORIES" to "श्रेणी",
            "Beauty, Salon & Personal Care" to "सौंदर्य, सलून आणि वैयक्तिक काळजी",
            "Restaurants, Hotels & Catering" to "रेस्टॉरंट, हॉटेल आणि कॅटरिंग",
            "Food Retail & Grocery" to "अन्न किरकोळ आणि किराणा",
            "Healthcare, Clinics & Diagnostics" to "आरोग्यसेवा, क्लिनिक आणि निदान",
            "Pharmacy, Medicines & Medical Equipment" to "फार्मसी, औषधे आणि वैद्यकीय उपकरणे",
            "Education & Training" to "शिक्षण आणि प्रशिक्षण",
            "Garments, Textile & Tailoring" to "वस्त्रे, कापड आणि शिंपी",
            "IT, Software & Digital Services" to "आयटी, सॉफ्टवेअर आणि डिजिटल सेवा",
            "Electronics, Electrical & Telecom" to "इलेक्ट्रॉनिक्स, इलेक्ट्रिकल आणि दूरसंचार",
            "Automobile, Transport & Travel" to "ऑटोमोबाईल, वाहतूक आणि प्रवास",
            "Banking, Finance & Insurance" to "बँकिंग, वित्त आणि विमा",
            "Construction Materials, Hardware & Industrial Goods" to "बांधकाम साहित्य, हार्डवेअर आणि औद्योगिक वस्तू",
            "Courier, Logistics & Warehousing" to "कुरिअर, लॉजिस्टिक्स आणि वेअरहाऊसिंग",
            "Professional & Consultancy Services" to "व्यावसायिक आणि सल्लागार सेवा",
            "Others" to "इतर",
            "GET STARTED" to "सुरू करा",
            "Already have an account? Sign In" to "आधीपासून खाते आहे? साइन इन करा",
            "Home" to "होम",
            "Light" to "लाइट",
            "Dark" to "डार्क",
            "Register Now" to "आता नोंदणी करा",
            "First time? Create your secure vault" to "पहिल्यांदा? तुमचा सुरक्षित व्हॉल्ट तयार करा",
            "Returning User?" to "परिचित वापरकर्ता?",
            "Business Owner" to "व्यवसाय मालक",
            "Sign in with email & password" to "ईमेल आणि पासवर्डने साइन इन करा",
            "Manager" to "व्यवस्थापक",
            "Access assigned businesses with code" to "कोडसह नियुक्त व्यवसायांमध्ये प्रवेश करा",
            "Owner Sign In" to "मालक साइन इन",
            "Access your business dashboard" to "तुमच्या व्यवसाय डॅशबोर्डमध्ये प्रवेश करा",
            "Email Address" to "ईमेल पत्ता",
            "Enter a valid email address" to "वैध ईमेल पत्ता प्रविष्ट करा",
            "Password" to "पासवर्ड",
            "Enter your password" to "तुमचा पासवर्ड प्रविष्ट करा",
            "Password is required" to "पासवर्ड आवश्यक आहे",
            "SECURE ACCESS" to "सुरक्षित प्रवेश",
            "Create Account" to "खाते तयार करा",
            "Set up your business document vault" to "तुमचा व्यवसाय दस्तऐवज व्हॉल्ट सेट करा",
            "Full Name" to "पूर्ण नाव",
            "Name is required" to "नाव आवश्यक आहे",
            "Mobile Number" to "मोबाइल क्रमांक",
            "Enter a valid 10-digit mobile number" to "वैध 10-अंकी मोबाइल क्रमांक प्रविष्ट करा",
            "8+ chars, upper, lower, digit, special" to "8+ अक्षरे, मोठी, लहान, अंक, विशेष",
            "Enter a password" to "पासवर्ड प्रविष्ट करा",
            "Weak" to "कमकुवत",
            "Fair" to "मध्यम",
            "Good" to "चांगले",
            "Strong" to "मजबूत",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "किमान 8 अक्षरे मोठी, लहान अक्षरे, अंक आणि विशेष चिन्हासह असावीत",
            "CREATE VAULT" to "व्हॉल्ट तयार करा",
            "Manager Access" to "व्यवस्थापक प्रवेश",
            "Enter access code provided by owner" to "मालकाने दिलेला प्रवेश कोड प्रविष्ट करा",
            "Access Code" to "प्रवेश कोड",
            "Invalid access code" to "अवैध प्रवेश कोड",
            "VERIFY & ACCESS" to "सत्यापित करा आणि प्रवेश करा",
            "Secure Business Locker for Your Business" to "तुमच्या व्यवसायासाठी सुरक्षित व्यवसाय लॉकर"
        ),
        "or" to mapOf(
            "Secure Business Document Vault" to "ସୁରକ୍ଷିତ ବ୍ୟବସାୟ ଦଲିଲ ଭଣ୍ଡାର",
            "Search" to "ଖୋଜ",
            "Bank-Grade Security" to "ବ୍ୟାଙ୍କ-ସ୍ତରୀୟ ସୁରକ୍ଷା",
            "Your business documents stay encrypted, private & safe in one vault." to "ଆପଣଙ୍କ ବ୍ୟବସାୟ ଦଲିଲଗୁଡ଼ିକ ଏକ ଭଣ୍ଡାରରେ ଏନକ୍ରିପ୍ଟ, ବ୍ୟକ୍ତିଗତ ଏବଂ ସୁରକ୍ଷିତ ରହିଥାଏ।",
            "Renewal Reminders" to "ନବୀକରଣ ସ୍ମାରକୀ",
            "Never miss an expiry - get timely alerts for every important document." to "ସମୟସୀମା କେବେ ବି ମିସ୍ କରନ୍ତୁ ନାହିଁ - ପ୍ରତ୍ୟେକ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଦଲିଲ ପାଇଁ ସମୟସୂଚିତ ସତର୍କ ସୂଚନା ପାଆନ୍ତୁ।",
            "DOCUMENTS YOU CAN STORE" to "ଆପଣ ସଂରକ୍ଷଣ କରିପାରିବେ ଯେଉଁ ଦଲିଲ",
            "GST Certificate" to "GST ପ୍ରମାଣପତ୍ର",
            "PAN Card" to "PAN କାର୍ଡ",
            "Aadhaar Card" to "ଆଧାର କାର୍ଡ",
            "FSSAI License" to "FSSAI ଲାଇସେନ୍ସ",
            "Trade License" to "ବ୍ୟାପାର ଲାଇସେନ୍ସ",
            "Shop & Est." to "ଦୋକାନ ଏବଂ ପ୍ରତିଷ୍ଠାନ",
            "Fire NOC" to "ଅଗ୍ନି NOC",
            "Udyam Reg." to "ଉଦ୍ୟମ ପଞ୍ଜୀକରଣ",
            "Drug License" to "ଔଷଧ ଲାଇସେନ୍ସ",
            "Factory License" to "କାରଖାନା ଲାଇସେନ୍ସ",
            "CATEGORIES" to "ବର୍ଗ",
            "Beauty, Salon & Personal Care" to "ସୌନ୍ଦର୍ଯ୍ୟ, ସାଲୁନ୍ ଏବଂ ବ୍ୟକ୍ତିଗତ ଯତ୍ନ",
            "Restaurants, Hotels & Catering" to "ରେସ୍ତୋରାଁ, ହୋଟେଲ ଏବଂ କ୍ୟାଟରିଂ",
            "Food Retail & Grocery" to "ଖାଦ୍ୟ ଖୁଚୁରା ଏବଂ କିରାଣା",
            "Healthcare, Clinics & Diagnostics" to "ସ୍ୱାସ୍ଥ୍ୟସେବା, କ୍ଲିନିକ୍ ଏବଂ ଡାଇଗ୍ନୋଷ୍ଟିକ୍ସ",
            "Pharmacy, Medicines & Medical Equipment" to "ଫାର୍ମାସି, ଔଷଧ ଏବଂ ଚିକିତ୍ସା ଉପକରଣ",
            "Education & Training" to "ଶିକ୍ଷା ଏବଂ ପ୍ରଶିକ୍ଷଣ",
            "Garments, Textile & Tailoring" to "ବସ୍ତ୍ର, ଲୁଗା ଏବଂ ସିଲେଇ",
            "IT, Software & Digital Services" to "ଆଇଟି, ସଫ୍ଟୱେର୍ ଏବଂ ଡିଜିଟାଲ ସେବା",
            "Electronics, Electrical & Telecom" to "ଇଲେକ୍ଟ୍ରୋନିକ୍ସ, ଇଲେକ୍ଟ୍ରିକାଲ ଏବଂ ଟେଲିକମ",
            "Automobile, Transport & Travel" to "ଅଟୋମୋବାଇଲ, ପରିବହନ ଏବଂ ଭ୍ରମଣ",
            "Banking, Finance & Insurance" to "ବ୍ୟାଙ୍କିଂ, ଅର୍ଥ ଏବଂ ବୀମା",
            "Construction Materials, Hardware & Industrial Goods" to "ନିର୍ମାଣ ସାମଗ୍ରୀ, ହାର୍ଡୱେର୍ ଏବଂ ଶିଳ୍ପ ସାମଗ୍ରୀ",
            "Courier, Logistics & Warehousing" to "କୁରିଅର, ଲଜିଷ୍ଟିକ୍ସ ଏବଂ ଗୋଦାମ",
            "Professional & Consultancy Services" to "ବୃତ୍ତିଗତ ଏବଂ ପରାମର୍ଶ ସେବା",
            "Others" to "ଅନ୍ୟାନ୍ୟ",
            "GET STARTED" to "ଆରମ୍ଭ କରନ୍ତୁ",
            "Already have an account? Sign In" to "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ ଅଛି? ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
            "Home" to "ହୋମ୍",
            "Light" to "ଲାଇଟ୍",
            "Dark" to "ଡାର୍କ",
            "Register Now" to "ବର୍ତ୍ତମାନ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
            "First time? Create your secure vault" to "ପ୍ରଥମ ଥର? ଆପଣଙ୍କ ସୁରକ୍ଷିତ ଭଣ୍ଡାର ତିଆରି କରନ୍ତୁ",
            "Returning User?" to "ପୁରୁଣା ଉପଭୋକ୍ତା?",
            "Business Owner" to "ବ୍ୟବସାୟ ମାଲିକ",
            "Sign in with email & password" to "ଇମେଲ୍ ଏବଂ ପାସୱାର୍ଡ଼ ସହ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
            "Manager" to "ପରିଚାଳକ",
            "Access assigned businesses with code" to "କୋଡ଼ ସହ ନିର୍ଦ୍ଧାରିତ ବ୍ୟବସାୟରେ ପ୍ରବେଶ କରନ୍ତୁ",
            "Owner Sign In" to "ମାଲିକ ସାଇନ୍ ଇନ୍",
            "Access your business dashboard" to "ଆପଣଙ୍କ ବ୍ୟବସାୟ ଡାସବୋର୍ଡରେ ପ୍ରବେଶ କରନ୍ତୁ",
            "Email Address" to "ଇମେଲ୍ ଠିକଣା",
            "Enter a valid email address" to "ଏକ ବୈଧ ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ",
            "Password" to "ପାସୱାର୍ଡ଼",
            "Enter your password" to "ଆପଣଙ୍କ ପାସୱାର୍ଡ଼ ଦିଅନ୍ତୁ",
            "Password is required" to "ପାସୱାର୍ଡ଼ ଆବଶ୍ୟକ",
            "SECURE ACCESS" to "ସୁରକ୍ଷିତ ପ୍ରବେଶ",
            "Create Account" to "ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ",
            "Set up your business document vault" to "ଆପଣଙ୍କ ବ୍ୟବସାୟ ଦଲିଲ ଭଣ୍ଡାର ସେଟ୍ ଅପ୍ କରନ୍ତୁ",
            "Full Name" to "ପୂରା ନାମ",
            "Name is required" to "ନାମ ଆବଶ୍ୟକ",
            "Mobile Number" to "ମୋବାଇଲ୍ ନମ୍ବର",
            "Enter a valid 10-digit mobile number" to "ଏକ ବୈଧ 10-ଅଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
            "8+ chars, upper, lower, digit, special" to "8+ ଅକ୍ଷର, ବଡ଼, ଛୋଟ, ଅଙ୍କ, ବିଶେଷ",
            "Enter a password" to "ପାସୱାର୍ଡ଼ ଦିଅନ୍ତୁ",
            "Weak" to "ଦୁର୍ବଳ",
            "Fair" to "ମଧ୍ୟମ",
            "Good" to "ଭଲ",
            "Strong" to "ମଜବୁତ",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "ଅତି କମ୍ରେ 8 ଅକ୍ଷର ବଡ଼, ଛୋଟ ଅକ୍ଷର, ଅଙ୍କ ଏବଂ ବିଶେଷ ଚିହ୍ନ ସହିତ ହେବା ଉଚିତ୍",
            "CREATE VAULT" to "ଭଣ୍ଡାର ତିଆରି କରନ୍ତୁ",
            "Manager Access" to "ପରିଚାଳକ ପ୍ରବେଶ",
            "Enter access code provided by owner" to "ମାଲିକ ଦେଇଥିବା ପ୍ରବେଶ କୋଡ଼ ଦିଅନ୍ତୁ",
            "Access Code" to "ପ୍ରବେଶ କୋଡ଼",
            "Invalid access code" to "ଅବୈଧ ପ୍ରବେଶ କୋଡ଼",
            "VERIFY & ACCESS" to "ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ପ୍ରବେଶ କରନ୍ତୁ",
            "Secure Business Locker for Your Business" to "ଆପଣଙ୍କ ବ୍ୟବସାୟ ପାଇଁ ସୁରକ୍ଷିତ ବ୍ୟବସାୟ ଲକର"
        ),
        "pa" to mapOf(
            "Secure Business Document Vault" to "ਸੁਰੱਖਿਅਤ ਕਾਰੋਬਾਰ ਦਸਤਾਵੇਜ਼ ਵਾਲਟ",
            "Search" to "ਖੋਜ",
            "Bank-Grade Security" to "ਬੈਂਕ-ਗਰੇਡ ਸੁਰੱਖਿਆ",
            "Your business documents stay encrypted, private & safe in one vault." to "ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਦੇ ਦਸਤਾਵੇਜ਼ ਇੱਕ ਵਾਲਟ ਵਿੱਚ ਏਨਕ੍ਰਿਪਟਡ, ਨਿੱਜੀ ਅਤੇ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦੇ ਹਨ।",
            "Renewal Reminders" to "ਨਵੀਨੀਕਰਨ ਯਾਦ-ਦਹਾਨੀਆਂ",
            "Never miss an expiry - get timely alerts for every important document." to "ਮਿਆਦ ਕਦੇ ਵੀ ਨਾ ਖੁੰਝਾਓ - ਹਰ ਮਹੱਤਵਪੂਰਨ ਦਸਤਾਵੇਜ਼ ਲਈ ਸਮੇਂ ਸਿਰ ਚੇਤਾਵਨੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
            "DOCUMENTS YOU CAN STORE" to "ਦਸਤਾਵੇਜ਼ ਜੋ ਤੁਸੀਂ ਸਟੋਰ ਕਰ ਸਕਦੇ ਹੋ",
            "GST Certificate" to "GST ਸਰਟੀਫਿਕੇਟ",
            "PAN Card" to "PAN ਕਾਰਡ",
            "Aadhaar Card" to "ਆਧਾਰ ਕਾਰਡ",
            "FSSAI License" to "FSSAI ਲਾਇਸੰਸ",
            "Trade License" to "ਵਪਾਰ ਲਾਇਸੰਸ",
            "Shop & Est." to "ਦੁਕਾਨ ਅਤੇ ਸਥਾਪਨਾ",
            "Fire NOC" to "ਫਾਇਰ NOC",
            "Udyam Reg." to "ਉਦਯਮ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
            "Drug License" to "ਦਵਾਈ ਲਾਇਸੰਸ",
            "Factory License" to "ਫੈਕਟਰੀ ਲਾਇਸੰਸ",
            "CATEGORIES" to "ਸ਼੍ਰੇਣੀਆਂ",
            "Beauty, Salon & Personal Care" to "ਸੁੰਦਰਤਾ, ਸੈਲੂਨ ਅਤੇ ਨਿੱਜੀ ਦੇਖਭਾਲ",
            "Restaurants, Hotels & Catering" to "ਰੈਸਟੋਰੈਂਟ, ਹੋਟਲ ਅਤੇ ਕੇਟਰਿੰਗ",
            "Food Retail & Grocery" to "ਭੋਜਨ ਪ੍ਰਚੂਨ ਅਤੇ ਕਿਰਾਨਾ",
            "Healthcare, Clinics & Diagnostics" to "ਸਿਹਤ ਸੰਭਾਲ, ਕਲੀਨਿਕ ਅਤੇ ਡਾਇਗਨੌਸਟਿਕਸ",
            "Pharmacy, Medicines & Medical Equipment" to "ਫਾਰਮੇਸੀ, ਦਵਾਈਆਂ ਅਤੇ ਡਾਕਟਰੀ ਉਪਕਰਣ",
            "Education & Training" to "ਸਿੱਖਿਆ ਅਤੇ ਸਿਖਲਾਈ",
            "Garments, Textile & Tailoring" to "ਵਸਤਰ, ਕੱਪੜਾ ਅਤੇ ਦਰਜ਼ੀ",
            "IT, Software & Digital Services" to "ਆਈਟੀ, ਸਾਫਟਵੇਅਰ ਅਤੇ ਡਿਜੀਟਲ ਸੇਵਾਵਾਂ",
            "Electronics, Electrical & Telecom" to "ਇਲੈਕਟ੍ਰੋਨਿਕਸ, ਇਲੈਕਟ੍ਰੀਕਲ ਅਤੇ ਦੂਰਸੰਚਾਰ",
            "Automobile, Transport & Travel" to "ਆਟੋਮੋਬਾਈਲ, ਆਵਾਜਾਈ ਅਤੇ ਯਾਤਰਾ",
            "Banking, Finance & Insurance" to "ਬੈਂਕਿੰਗ, ਵਿੱਤ ਅਤੇ ਬੀਮਾ",
            "Construction Materials, Hardware & Industrial Goods" to "ਉਸਾਰੀ ਸਮੱਗਰੀ, ਹਾਰਡਵੇਅਰ ਅਤੇ ਉਦਯੋਗਿਕ ਸਮਾਨ",
            "Courier, Logistics & Warehousing" to "ਕੋਰੀਅਰ, ਲੌਜਿਸਟਿਕਸ ਅਤੇ ਵੇਅਰਹਾਊਸਿੰਗ",
            "Professional & Consultancy Services" to "ਪੇਸ਼ੇਵਰ ਅਤੇ ਸਲਾਹ ਸੇਵਾਵਾਂ",
            "Others" to "ਹੋਰ",
            "GET STARTED" to "ਸ਼ੁਰੂ ਕਰੋ",
            "Already have an account? Sign In" to "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ? ਸਾਈਨ ਇਨ ਕਰੋ",
            "Home" to "ਹੋਮ",
            "Light" to "ਲਾਈਟ",
            "Dark" to "ਡਾਰਕ",
            "Register Now" to "ਹੁਣ ਰਜਿਸਟਰ ਕਰੋ",
            "First time? Create your secure vault" to "ਪਹਿਲੀ ਵਾਰ? ਆਪਣਾ ਸੁਰੱਖਿਅਤ ਵਾਲਟ ਬਣਾਓ",
            "Returning User?" to "ਪੁਰਾਣਾ ਉਪਭੋਗਤਾ?",
            "Business Owner" to "ਕਾਰੋਬਾਰ ਮਾਲਕ",
            "Sign in with email & password" to "ਈਮੇਲ ਅਤੇ ਪਾਸਵਰਡ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ",
            "Manager" to "ਪ੍ਰਬੰਧਕ",
            "Access assigned businesses with code" to "ਕੋਡ ਨਾਲ ਨਿਰਧਾਰਤ ਕਾਰੋਬਾਰਾਂ ਤੱਕ ਪਹੁੰਚ ਕਰੋ",
            "Owner Sign In" to "ਮਾਲਕ ਸਾਈਨ ਇਨ",
            "Access your business dashboard" to "ਆਪਣੇ ਕਾਰੋਬਾਰ ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚ ਕਰੋ",
            "Email Address" to "ਈਮੇਲ ਪਤਾ",
            "Enter a valid email address" to "ਮਾਨਤਾ-ਯੋਗ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ",
            "Password" to "ਪਾਸਵਰਡ",
            "Enter your password" to "ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
            "Password is required" to "ਪਾਸਵਰਡ ਲੋੜੀਂਦਾ ਹੈ",
            "SECURE ACCESS" to "ਸੁਰੱਖਿਅਤ ਪਹੁੰਚ",
            "Create Account" to "ਖਾਤਾ ਬਣਾਓ",
            "Set up your business document vault" to "ਆਪਣਾ ਕਾਰੋਬਾਰ ਦਸਤਾਵੇਜ਼ ਵਾਲਟ ਸੈੱਟ ਕਰੋ",
            "Full Name" to "ਪੂਰਾ ਨਾਮ",
            "Name is required" to "ਨਾਮ ਲੋੜੀਂਦਾ ਹੈ",
            "Mobile Number" to "ਮੋਬਾਈਲ ਨੰਬਰ",
            "Enter a valid 10-digit mobile number" to "ਮਾਨਤਾ-ਯੋਗ 10-ਅੰਕ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
            "8+ chars, upper, lower, digit, special" to "8+ ਅੱਖਰ, ਵੱਡੇ, ਛੋਟੇ, ਅੰਕ, ਖਾਸ",
            "Enter a password" to "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
            "Weak" to "ਕਮਜ਼ੋਰ",
            "Fair" to "ਮੱਧਮ",
            "Good" to "ਚੰਗਾ",
            "Strong" to "ਮਜ਼ਬੂਤ",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ ਵੱਡੇ, ਛੋਟੇ ਅੱਖਰ, ਅੰਕ ਅਤੇ ਖਾਸ ਚਿੰਨ੍ਹ ਨਾਲ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ",
            "CREATE VAULT" to "ਵਾਲਟ ਬਣਾਓ",
            "Manager Access" to "ਪ੍ਰਬੰਧਕ ਪਹੁੰਚ",
            "Enter access code provided by owner" to "ਮਾਲਕ ਦੁਆਰਾ ਦਿੱਤਾ ਐਕਸੈਸ ਕੋਡ ਦਰਜ ਕਰੋ",
            "Access Code" to "ਐਕਸੈਸ ਕੋਡ",
            "Invalid access code" to "ਅਵੈਧ ਐਕਸੈਸ ਕੋਡ",
            "VERIFY & ACCESS" to "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਪਹੁੰਚ ਕਰੋ",
            "Secure Business Locker for Your Business" to "ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਲਈ ਸੁਰੱਖਿਅਤ ਕਾਰੋਬਾਰ ਲਾਕਰ"
        ),
        "ta" to mapOf(
            "Secure Business Document Vault" to "பாதுகாப்பான வணிக ஆவண பெட்டகம்",
            "Search" to "தேடு",
            "Bank-Grade Security" to "வங்கி-தர பாதுகாப்பு",
            "Your business documents stay encrypted, private & safe in one vault." to "உங்கள் வணிக ஆவணங்கள் ஒரே பெட்டகத்தில் குறியாக்கப்பட்டு, தனிப்பட்டதாகவும் பாதுகாப்பாகவும் இருக்கும்.",
            "Renewal Reminders" to "புதுப்பித்தல் நினைவூட்டல்கள்",
            "Never miss an expiry - get timely alerts for every important document." to "காலாவதியை ஒருபோதும் தவறவிடாதீர்கள் - ஒவ்வொரு முக்கிய ஆவணத்திற்கும் சரியான நேரத்தில் எச்சரிக்கைகளைப் பெறுங்கள்.",
            "DOCUMENTS YOU CAN STORE" to "நீங்கள் சேமிக்கக்கூடிய ஆவணங்கள்",
            "GST Certificate" to "GST சான்றிதழ்",
            "PAN Card" to "PAN அட்டை",
            "Aadhaar Card" to "ஆதார் அட்டை",
            "FSSAI License" to "FSSAI உரிமம்",
            "Trade License" to "வர்த்தக உரிமம்",
            "Shop & Est." to "கடை மற்றும் நிறுவனம்",
            "Fire NOC" to "தீ NOC",
            "Udyam Reg." to "உத்யம் பதிவு",
            "Drug License" to "மருந்து உரிமம்",
            "Factory License" to "தொழிற்சாலை உரிமம்",
            "CATEGORIES" to "வகைகள்",
            "Beauty, Salon & Personal Care" to "அழகு, சலூன் & தனிப்பட்ட பராமரிப்பு",
            "Restaurants, Hotels & Catering" to "உணவகம், ஹோட்டல் & கேட்டரிங்",
            "Food Retail & Grocery" to "உணவு சில்லறை & மளிகை",
            "Healthcare, Clinics & Diagnostics" to "சுகாதாரம், கிளினிக்குகள் & நோயறிதல்",
            "Pharmacy, Medicines & Medical Equipment" to "மருந்தகம், மருந்துகள் & மருத்துவ உபகரணங்கள்",
            "Education & Training" to "கல்வி & பயிற்சி",
            "Garments, Textile & Tailoring" to "ஆடை, ஜவுளி & தையல்",
            "IT, Software & Digital Services" to "ஐடி, மென்பொருள் & டிஜிட்டல் சேவைகள்",
            "Electronics, Electrical & Telecom" to "மின்னணுவியல், மின் & தொலைத்தொடர்பு",
            "Automobile, Transport & Travel" to "வாகனம், போக்குவரத்து & பயணம்",
            "Banking, Finance & Insurance" to "வங்கியியல், நிதி & காப்பீடு",
            "Construction Materials, Hardware & Industrial Goods" to "கட்டுமான பொருட்கள், வன்பொருள் & தொழில்துறை பொருட்கள்",
            "Courier, Logistics & Warehousing" to "கூரியர், தளவாடங்கள் & கிடங்கு",
            "Professional & Consultancy Services" to "தொழில்முறை & ஆலோசனை சேவைகள்",
            "Others" to "மற்றவை",
            "GET STARTED" to "தொடங்கவும்",
            "Already have an account? Sign In" to "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
            "Home" to "முகப்பு",
            "Light" to "லைட்",
            "Dark" to "டார்க்",
            "Register Now" to "இப்போது பதிவு செய்க",
            "First time? Create your secure vault" to "முதல் முறையா? உங்கள் பாதுகாப்பான பெட்டகத்தை உருவாக்குங்கள்",
            "Returning User?" to "முன்பு பயன்படுத்தியவரா?",
            "Business Owner" to "வணிக உரிமையாளர்",
            "Sign in with email & password" to "மின்னஞ்சல் & கடவுச்சொல்லுடன் உள்நுழைக",
            "Manager" to "மேலாளர்",
            "Access assigned businesses with code" to "குறியீட்டுடன் ஒதுக்கப்பட்ட வணிகங்களை அணுகவும்",
            "Owner Sign In" to "உரிமையாளர் உள்நுழைவு",
            "Access your business dashboard" to "உங்கள் வணிக டாஷ்போர்டை அணுகவும்",
            "Email Address" to "மின்னஞ்சல் முகவரி",
            "Enter a valid email address" to "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்",
            "Password" to "கடவுச்சொல்",
            "Enter your password" to "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
            "Password is required" to "கடவுச்சொல் தேவை",
            "SECURE ACCESS" to "பாதுகாப்பான அணுகல்",
            "Create Account" to "கணக்கு உருவாக்கு",
            "Set up your business document vault" to "உங்கள் வணிக ஆவண பெட்டகத்தை அமைக்கவும்",
            "Full Name" to "முழு பெயர்",
            "Name is required" to "பெயர் தேவை",
            "Mobile Number" to "மொபைல் எண்",
            "Enter a valid 10-digit mobile number" to "சரியான 10-இலக்க மொபைல் எண்ணை உள்ளிடவும்",
            "8+ chars, upper, lower, digit, special" to "8+ எழுத்துகள், பெரிய, சிறிய, எண், சிறப்பு",
            "Enter a password" to "கடவுச்சொல்லை உள்ளிடவும்",
            "Weak" to "பலவீனம்",
            "Fair" to "நடுத்தரம்",
            "Good" to "நல்லது",
            "Strong" to "வலுவான",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "குறைந்தது 8 எழுத்துகள் பெரிய, சிறிய எழுத்து, எண் மற்றும் சிறப்பு எழுத்துடன் இருக்க வேண்டும்",
            "CREATE VAULT" to "பெட்டகம் உருவாக்கு",
            "Manager Access" to "மேலாளர் அணுகல்",
            "Enter access code provided by owner" to "உரிமையாளர் வழங்கிய அணுகல் குறியீட்டை உள்ளிடவும்",
            "Access Code" to "அணுகல் குறியீடு",
            "Invalid access code" to "தவறான அணுகல் குறியீடு",
            "VERIFY & ACCESS" to "சரிபார்த்து அணுகவும்",
            "Secure Business Locker for Your Business" to "உங்கள் வணிகத்திற்கான பாதுகாப்பான வணிக லாக்கர்"
        ),
        "te" to mapOf(
            "Secure Business Document Vault" to "సురక్షిత వ్యాపార పత్ర వాల్ట్",
            "Search" to "వెతకండి",
            "Bank-Grade Security" to "బ్యాంక్-గ్రేడ్ భద్రత",
            "Your business documents stay encrypted, private & safe in one vault." to "మీ వ్యాపార పత్రాలు ఒకే వాల్ట్లో ఎన్క్రిప్టెడ్, ప్రైవేట్ మరియు సురక్షితంగా ఉంటాయి.",
            "Renewal Reminders" to "పునరుద్ధరణ రిమైండర్లు",
            "Never miss an expiry - get timely alerts for every important document." to "గడువును ఎప్పటికీ మిస్ చేయకండి - ప్రతి ముఖ్యమైన పత్రానికి సమయానికి హెచ్చరికలు పొందండి.",
            "DOCUMENTS YOU CAN STORE" to "మీరు నిల్వ చేయగల పత్రాలు",
            "GST Certificate" to "GST సర్టిఫికెట్",
            "PAN Card" to "PAN కార్డ్",
            "Aadhaar Card" to "ఆధార్ కార్డ్",
            "FSSAI License" to "FSSAI లైసెన్స్",
            "Trade License" to "వ్యాపార లైసెన్స్",
            "Shop & Est." to "షాప్ మరియు ఎస్టాబ్లిష్మెంట్",
            "Fire NOC" to "అగ్ని NOC",
            "Udyam Reg." to "ఉద్యమ్ రిజిస్ట్రేషన్",
            "Drug License" to "మందుల లైసెన్స్",
            "Factory License" to "ఫ్యాక్టరీ లైసెన్స్",
            "CATEGORIES" to "వర్గాలు",
            "Beauty, Salon & Personal Care" to "అందం, సెలూన్ & వ్యక్తిగత సంరక్షణ",
            "Restaurants, Hotels & Catering" to "రెస్టారెంట్, హోటల్ & క్యాటరింగ్",
            "Food Retail & Grocery" to "ఫుడ్ రిటైల్ & కిరాణా",
            "Healthcare, Clinics & Diagnostics" to "హెల్త్కేర్, క్లినిక్లు & డయాగ్నోస్టిక్స్",
            "Pharmacy, Medicines & Medical Equipment" to "ఫార్మసీ, మందులు & వైద్య పరికరాలు",
            "Education & Training" to "విద్య & శిక్షణ",
            "Garments, Textile & Tailoring" to "వస్త్రాలు, టెక్స్టైల్ & టైలరింగ్",
            "IT, Software & Digital Services" to "ఐటీ, సాఫ్ట్వేర్ & డిజిటల్ సేవలు",
            "Electronics, Electrical & Telecom" to "ఎలక్ట్రానిక్స్, ఎలక్ట్రికల్ & టెలికాం",
            "Automobile, Transport & Travel" to "ఆటోమొబైల్, రవాణా & ప్రయాణం",
            "Banking, Finance & Insurance" to "బ్యాంకింగ్, ఫైనాన్స్ & బీమా",
            "Construction Materials, Hardware & Industrial Goods" to "నిర్మాణ సామగ్రి, హార్డ్వేర్ & పారిశ్రామిక వస్తువులు",
            "Courier, Logistics & Warehousing" to "కొరియర్, లాజిస్టిక్స్ & వేర్హౌసింగ్",
            "Professional & Consultancy Services" to "ప్రొఫెషనల్ & కన్సల్టెన్సీ సేవలు",
            "Others" to "ఇతరాలు",
            "GET STARTED" to "ప్రారంభించండి",
            "Already have an account? Sign In" to "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
            "Home" to "హోమ్",
            "Light" to "లైట్",
            "Dark" to "డార్క్",
            "Register Now" to "ఇప్పుడే నమోదు చేయండి",
            "First time? Create your secure vault" to "మొదటిసారి? మీ సురక్షిత వాల్ట్ను సృష్టించండి",
            "Returning User?" to "తిరిగి వచ్చిన వినియోగదారా?",
            "Business Owner" to "వ్యాపార యజమాని",
            "Sign in with email & password" to "ఇమెయిల్ & పాస్వర్డ్తో సైన్ ఇన్ చేయండి",
            "Manager" to "మేనేజర్",
            "Access assigned businesses with code" to "కోడ్తో కేటాయించిన వ్యాపారాలను యాక్సెస్ చేయండి",
            "Owner Sign In" to "యజమాని సైన్ ఇన్",
            "Access your business dashboard" to "మీ వ్యాపార డాష్బోర్డ్ను యాక్సెస్ చేయండి",
            "Email Address" to "ఇమెయిల్ చిరునామా",
            "Enter a valid email address" to "చెల్లుబాటు అయ్యే ఇమెయిల్ చిరునామాను నమోదు చేయండి",
            "Password" to "పాస్వర్డ్",
            "Enter your password" to "మీ పాస్వర్డ్ను నమోదు చేయండి",
            "Password is required" to "పాస్వర్డ్ అవసరం",
            "SECURE ACCESS" to "సురక్షిత యాక్సెస్",
            "Create Account" to "ఖాతా సృష్టించండి",
            "Set up your business document vault" to "మీ వ్యాపార పత్ర వాల్ట్ను సెటప్ చేయండి",
            "Full Name" to "పూర్తి పేరు",
            "Name is required" to "పేరు అవసరం",
            "Mobile Number" to "మొబైల్ నంబర్",
            "Enter a valid 10-digit mobile number" to "చెల్లుబాటు అయ్యే 10-అంకెల మొబైల్ నంబర్ను నమోదు చేయండి",
            "8+ chars, upper, lower, digit, special" to "8+ అక్షరాలు, పెద్ద, చిన్న, అంకె, ప్రత్యేక",
            "Enter a password" to "పాస్వర్డ్ను నమోదు చేయండి",
            "Weak" to "బలహీనం",
            "Fair" to "మధ్యస్థం",
            "Good" to "మంచిది",
            "Strong" to "బలమైన",
            "Must be 8+ chars with uppercase, lowercase, digit & special char" to "కనీసం 8 అక్షరాలు పెద్ద, చిన్న అక్షరాలు, అంకె మరియు ప్రత్యేక గుర్తుతో ఉండాలి",
            "CREATE VAULT" to "వాల్ట్ సృష్టించండి",
            "Manager Access" to "మేనేజర్ యాక్సెస్",
            "Enter access code provided by owner" to "యజమాని అందించిన యాక్సెస్ కోడ్ను నమోదు చేయండి",
            "Access Code" to "యాక్సెస్ కోడ్",
            "Invalid access code" to "చెల్లని యాక్సెస్ కోడ్",
            "VERIFY & ACCESS" to "ధృవీకరించి యాక్సెస్ చేయండి",
            "Secure Business Locker for Your Business" to "మీ వ్యాపారం కోసం సురక్షిత వ్యాపార లాకర్"
        )
    )

    fun get(code: String, key: String): String =
        translations[code]?.get(key) ?: key
}
