spring.application.name=DukaanLocker

spring.datasource.url=jdbc:postgresql://54.152.221.36:5432/dukaanlocker
spring.datasource.username=anjalikashyap
spring.datasource.password=Anjali@1901

spring.datasource.driver-class-name=org.postgresql.Driver

Type: PostgreSQL
Protocol: TCP
Port: 5432
Source: My IP

spring.jpa.properties.hibernate.format_sql=true

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.scan.packages=com.Dukaan.DukaanLocker,com.shoplocker.fssai

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# FSSAI Service Configuration
fssai.portal.url=https://foscos.fssai.gov.in/
fssai.scraper.timeout-seconds=60
fssai.download.path=downloads/fssai/

server.port=8081

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true